#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/channel/UCBwtRVFAC9VkFfcdsHUq66w permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
