#!/usr/bin/env bash
# Displays "Best School" 10 times, 4 bad luck, 8 good luck

while ((i < 10))
do

	((i++))
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
